
import math
import argparse
import random
import motiflib

extended_help = """
%(prog)s is a program that simulates promoter regions by embedding binding sites
in random sequences. The sites are randomly generated from a motif described in
JASPAR format and the sequences are generated by simple base composition.
"""

parser = argparse.ArgumentParser(
	description='Embeds instances of a motif into random sequences',
	epilog=extended_help)
parser.add_argument('--jasparfile', required=True, type=str,
	metavar='<str>', help='jaspar file')
parser.add_argument('--numseqp', required=False, type=int, default=5,
	metavar='<int>', help='number of positive sequences to generate [%(default)i]')

parser.add_argument('--numseqn', required=False, type=int, default=5,
	metavar='<int>', help='number of negative sequences to generate [%(default)i]')

parser.add_argument('--seqlen', required=False, type=int, default=100,
	metavar='<int>', help='length of sequences to generate [%(default)i]')
parser.add_argument('--mps', required=False, type=int, default=1,
	metavar='<int>', help='number of motifs per seqeunce [%(default)i]')
parser.add_argument('--freq', required=False, type=float, default=0.9,
	metavar='<float>', help='optional floating point argument [%(default).3f]')
parser.add_argument('--PA', required=False, type=float, default=0.25,
	metavar='<float>', help='optional floating point argument [%(default).3f]')
parser.add_argument('--PC', required=False, type=float, default=0.25,
	metavar='<float>', help='optional floating point argument [%(default).3f]')
parser.add_argument('--PG', required=False, type=float, default=0.25,
	metavar='<float>', help='optional floating point argument [%(default).3f]')
parser.add_argument('--PT', required=False, type=float, default=0.25,
	metavar='<float>', help='optional floating point argument [%(default).3f]')
parser.add_argument('--bothstrands', action='store_true',
	help='on/off switch')
arg = parser.parse_args()

def generate_seq(numseqp, numseqn, seqlen, PA, PC, PG, PT):
	seq = []
	for i in range(0,arg.seqlen): # seq is a list from 0 to whatever you chose
		r  = random.random()
		if r < PA:             seq += 'a'
		elif r < PA + PC:      seq += 'c'
		elif r < PA + PC + PG: seq += 'g'
		else:                  seq += 't'
	return seq

# I wanna put something here that will notice when a jaspar seq is the negative strand and insert the sequence 3' to 5'

motif = motiflib.read_JASPAR(arg.jasparfile)
pos_seqs = range(0, arg.numseqp)
#neg_seqs = range(0, arg.numseqn)
for i in pos_seqs:
	seq = (generate_seq(arg.numseqn, arg.numseqp, arg.seqlen, arg.PA, arg.PC, arg.PG, arg.PT)) #this makes a sequence for all 10 spots in the range
	r = random.random() #this randomizes shit
	places = []

	if r < arg.freq: # if randomness is under a certain frequency
		for j in range(0,arg.mps):
			site = motiflib.generate_site(motif) #for every motif in it's sequence, a motif is generated
            #motif.reverse(odd) #N
			assert(len(motif)== len(site)) # this is where the motif gets put in the sequence
			place = random.randint(0, len(seq)-len(motif))
			places.append(f'{place}+')
			for k in range(0,len(site)):
				seq[place+k] = site[k]

	print(f'>seq-{i} {places}')
	print(''.join(seq))

